# Importing libraries and CSV

## Libraries

In [1]:
# SQL
import pymysql
import sqlalchemy as alch # python -m pip install --upgrade 'sqlalchemy<2.0'

# Get pass for password
from getpass import getpass

# df 
import pandas as pd
import numpy as np 

# Visualization
import plotly.express as px

## Importing CSV

In [2]:
# Check why I have to share all the path 

df = pd.read_csv(r"C:\Users\DavidVicente\Desktop\IronHack\Git_Project_Repos\Project_4_Superstore-Sales-Visualization-\Data\Sample - Superstore.csv", encoding='latin')
df.sample(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
5428,5429,CA-2016-113096,9/2/2016,9/4/2016,First Class,SZ-20035,Sam Zeldin,Home Office,United States,San Francisco,...,94122,West,OFF-ST-10003455,Office Supplies,Storage,"Tenex File Box, Personal Filing Tote with Lid,...",46.530,3,0.0,12.0978
1183,1184,CA-2017-138779,1/14/2017,1/15/2017,First Class,RB-19570,Rob Beeghly,Consumer,United States,Jacksonville,...,28540,South,TEC-PH-10003655,Technology,Phones,Sannysis Cute Owl Design Soft Skin Case Cover ...,7.920,5,0.2,0.6930
4386,4387,CA-2016-156811,10/27/2016,11/2/2016,Standard Class,BP-11095,Bart Pistole,Corporate,United States,San Francisco,...,94122,West,OFF-AP-10001366,Office Supplies,Appliances,Staple holder,43.920,4,0.0,11.8584
8428,8429,US-2017-132220,11/12/2017,11/16/2017,Standard Class,DJ-13510,Don Jones,Corporate,United States,Tempe,...,85281,West,TEC-AC-10004227,Technology,Accessories,SanDisk Ultra 16 GB MicroSDHC Class 10 Memory ...,62.352,6,0.2,-10.9116
2889,2890,CA-2017-164049,11/2/2017,11/6/2017,Standard Class,KH-16630,Ken Heidel,Corporate,United States,Seattle,...,98105,West,OFF-PA-10000791,Office Supplies,Paper,"Wirebound Message Books, Four 2 3/4 x 5 Forms ...",23.850,5,0.0,10.7325

In [3]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

# Dataframe Transformation

In [4]:
def df_transformation(df):

    # Converting both columns into date data type

    df['Order Date'] = pd.to_datetime(df['Order Date'])
    df['Ship Date'] = pd.to_datetime(df['Ship Date'])

    # Renaming df columns

    df.rename(columns={"Row ID": "Row_ID",
                       "Order ID": "Order_ID", 
                       "Order Date": "Order_Date", 
                       "Ship Date": "Ship_Date", 
                       "Ship Mode": "Ship_Mode",
                       "Customer ID": "Customer_ID",
                       "Customer Name": "Customer_Name",
                       "Postal Code": "Postal_Code", 
                       "Product ID": "Product_ID", 
                       "Product Name": "Product_Name"}, inplace=True)


    # Adding new column with days between order and shipping

    df['Total_Shipping_Days'] = (df['Ship_Date'] - df['Order_Date']).dt.days
    
    # Percentage of profit per sale
    
    df['Profit_Percentage'] = round((df['Profit'] / df['Sales']),2)
    
    # Product Unit price
    
    df['Unit_Price'] = round((df['Sales'] / df['Quantity']),2)

In [5]:
df_transformation(df)

In [6]:
df.sample(5)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit,Total_Shipping_Days,Profit_Percentage,Unit_Price
445,446,CA-2016-115756,2016-09-05,2016-09-07,Second Class,PK-19075,Pete Kriz,Consumer,United States,Detroit,...,Office Supplies,Labels,Avery 520,22.050,7,0.0,10.5840,2,0.48,3.15
263,264,US-2014-106992,2014-09-19,2014-09-21,Second Class,SB-20290,Sean Braxton,Corporate,United States,Houston,...,Technology,Machines,Xerox WorkCentre 6505DN Laser Multifunction Pr...,2519.958,7,0.4,-251.9958,2,-0.10,359.99
804,805,CA-2017-135783,2017-04-22,2017-04-24,First Class,GM-14440,Gary McGarr,Consumer,United States,San Francisco,...,Furniture,Furnishings,"Eldon Stackable Tray, Side-Load, Legal, Smoke",18.280,2,0.0,6.2152,2,0.34,9.14
6251,6252,CA-2014-101147,2014-12-02,2014-12-04,First Class,MC-17575,Matt Collins,Consumer,United States,Chicago,...,Office Supplies,Appliances,Staple holder,2.394,1,0.8,-6.3441,2,-2.65,2.39
6299,6300,CA-2017-107314,2017-11-30,2017-12-03,First Class,MZ-17335,Maria Zettner,Home Office,United States,San Francisco,...,Furniture,Furnishings,Contemporary Borderless Frame,25.830,3,0.0,9.5571,3,0.37,8.61

# Uploading to db

- Setting connection to SQL

In [ ]:
password = getpass("Please enter your password: ")

dbName = "superstore"

connectionData=f"mysql+pymysql://root:{password}@localhost/{dbName}"

engine = alch.create_engine(connectionData)

# Export to csv

In [7]:
df.to_csv(r'C:\Users\DavidVicente\Desktop\IronHack\Git_Project_Repos\Project_4_Superstore-Sales-Visualization-\Data\superstore_df.csv')